select * from customer limit 20
--Q-1:WHAT IS THE TOTAL REVENUE GENERATED BY MALE VS FEMALE CUSTOMERS
select gender, SUM(purchase_amount) as revenue
from customer
group by gender
--Q-2:WHICH CUSTOMERS USED A DISCOUNT BUT STILL SPENT MORE THAN AVG PURCHASE AMOUNT?
SELECT customer_id, purchase_amount
from customer
WHERE discount_applied ='Yes' AND
purchase_amount >= (select AVG(purchase_amount) from customer)
--Q-3:which are the top 5 products with highest avg review rating? 
--(products with consistent rating can also be sold at premium price)
SELECT item_purchased, round(avg( review_rating:: numeric),2) AS "Avg_product_rating"
from customer
GROUP BY item_purchased
ORDER BY avg(review_rating) DESC limit 5;

--Q-4:Compare the avg purchase amounts between standard and express shipping?
--if customer spends more in express shipping, then buisiness should invest more in faster delivery options
SELECT round(avg(purchase_amount),2) AS avg_purchase_amount,shipping_type
from customer
where shipping_type in ('Express','Standard')
group by shipping_type

--Q-5:Do subscribed customers spend more?Compare average spend and total revenue.
-- the results will tell us whether the subscription program is working out or not
SELECT subscription_status,
count(customer_id) as total_customers,
round(AVG(purchase_amount),2) AS avg_spend,
SUM(purchase_amount) AS total_revenue
from customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend desc;

--Q-6:WHICH 5 PRODUCTS HAVE THE HIGHEST PERCENTAGE OF PURCHASES WITH DISCOUNTS APPLIED?
--this helps in knowing which pdts rely heavily on discounting
SELECT item_purchased,
ROUND(
    100*SUM(CASE WHEN discount_applied = 'Yes' 
	THEN 1 ELSE 0 END)
    / COUNT(*), 2
) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
--Q7. Segment customers into New, Returning, and Loyal based on their total
--number of previous purchases, and show the count of each segment.
WITH customer_type AS
(SELECT customer_id,previous_purchases,
 CASE
     WHEN previous_purchases = 2 THEN 'NEW'
     WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
     ELSE 'Loyal'
END AS customer_segment
FROM customer)
SELECT customer_segment,count(*) AS num
FROM customer_type
GROUP BY customer_segment

--Q8. What are the top 3 most purchased products within each category?
with item_counts AS (
SELECT category,item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() OVER (PARTITION BY category 
order by count (customer_id) desc) as item_rank
from customer
group by category , item_purchased)
SELECT item_rank, category, item_purchased,total_orders
from item_counts
where item_rank<=3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
--if loyal customers are not subscribing, then it means that subscription is not attractuve to the customers 
SELECT subscription_status,
       COUNT(*) AS num_customers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;
--Q10. What is the revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) AS total_revenue
from customer 
group by age_group
order by total_revenue DESC;





































